# Generated by Django 3.1.4 on 2021-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20210722_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(help_text='Ingrese el tipo de género (p. ej. Ciencia Ficción, Poesía Francesa etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='lenguaje',
            name='nombre',
            field=models.CharField(help_text='Introduzca el idioma del libro.', max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(help_text='seleccione un genero para este libro.', to='catalogo.Genero'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(help_text='hasta 13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
