# Generated by Django 3.1.4 on 2021-07-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20210723_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplarespecifico',
            options={'ordering': ['devolucion']},
        ),
        migrations.RenameField(
            model_name='ejemplarespecifico',
            old_name='due_back',
            new_name='devolucion',
        ),
    ]
