# Generated by Django 3.1.4 on 2021-08-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20210831_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejemplarespecifico',
            old_name='prestados',
            new_name='prestatario',
        ),
    ]
