# Generated by Django 3.1.4 on 2021-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20210831_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplarespecifico',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('p', 'Prestado'), ('d', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Estatus en que se encuentra actualmente el ejemplar específico.', max_length=1),
        ),
    ]
