# Generated by Django 3.1.4 on 2021-09-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20210902_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplarespecifico',
            options={'ordering': ['devolucion'], 'permissions': (('puedeMarcarRetornado', 'Coloca el libro como retornado'),)},
        ),
    ]
