# Generated by Django 3.1.4 on 2021-09-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20210903_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplarespecifico',
            options={'ordering': ['devolucion'], 'permissions': (('can_mark_Retornado', 'Coloca el libro como retornado'),)},
        ),
    ]
