# Generated by Django 3.1.4 on 2021-09-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20210903_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplarespecifico',
            options={'ordering': ['devolucion'], 'permissions': (('puedeMarcarRetornado', 'Puede marcar el libro como retornado.'), ('unPermisoX', 'Un permiso de hacer X cosa.'))},
        ),
    ]
