# Generated by Django 3.1.4 on 2021-09-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20210908_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplarespecifico',
            options={'ordering': ['devolucion'], 'permissions': (('permisoBibliotecario1', 'Permiso tipo 1 sólo para bibliotecarios'), ('permisoBibliotecario2', 'Permiso tipo 2 sólo para bibliotecarios'), ('unPermisoX', 'Un permiso de hacer x cosa a x usuario.'))},
        ),
    ]
